export const getDescription = (name) => {
    switch (name) {
        case 'arrondissement01':
        case 'arrondissement02':
            return {title: `1st and 2nd Arrondissement`, subtitle: `The Heart of Paris`, desc: `Among the oldest city neighborhoods, the 1st and 2nd Arrondissements are the very center of Paris on the Right Bank. Here is where you'll find the Jardin des Tuileries, Rue de Rivoli and Place Vendôme, to name a few historic sites. Reasons to stay here are many — easy access to the Louvre, shopping on Rue St Honoré, visiting Place de la Concorde and the gardens of Palais Royal. Let's explore our top-rated things to do in the heart of Paris.`}
        case 'arrondissement03':
        case 'arrondissement04':
            return {title: `3rd and 4th Arrondissement`, subtitle: `The Marais`, desc: `The Marais (comprising the 3rd and 4th Arrondissements) is one of the most popular neighborhoods of Paris. And no wonder — it's replete with old-world charm, narrow cobblestone streets, hidden courtyards and gardens, a multitude of mansions (called hôtels particuliers), a vibrant Jewish community, and a thriving gallery and cafe culture. Let's explore the best things to do in the Marais.`}
        case 'arrondissement05':
            return {title: `5th Arrondissement`, subtitle: `The Latin Quarter`, desc: `The Latin Quarter's winding, cobblestone streets remind us of what the medieval city of Paris looked like, when the original scholars of the Sorbonne university roamed the streets speaking Latin. Built by the Romans, it is, in fact, the oldest district in Paris. Today, the Latin Quarter (the 5th Arrondissement) retains its ancient feel as it was largely spared the sweeping renovations of Baron Haussmann. From the food stalls on Rue Mouffetard to the Jardin des Plantes, the Pantheon, and the historic Cluny Museum, there's a lot to see and do in the Latin Quarter.`}
        case 'arrondissement06':
            return {title: `6th Arrondissement`, subtitle: `Saint Germain des Prés`, desc: `The 6th Arrondissement is well-known for its many fine restaurants, food stores, and cafés, and it is one of the prettiest areas in Paris. Guests love that they can experience daily life as the Parisians do by shopping at the same local bakeries and patisseries, fruit and vegetable shops, butchers, cheese shops, and small supermarkets.`}
        case 'arrondissement07':
            return {title: `7th Arrondissement`, subtitle: `Historic Monuments and the Eiffel Tower`, desc: `The 7th Arrondissement is on the Left Bank and is home to the Eiffel Tower, popular market street Rue Cler, Rue St. Dominique, and the d'Orsay Museum. It's a wealthy Paris neighborhood filled with charming Left Bank hotels, bistros and leafy streets.`}
        case 'arrondissement08':
            return {title: `8th Arrondissement`, subtitle: `Champs Elysées`, desc: `The 8th Arrondissement, on the Right Bank, borders on the 16th and 17th Arrondissement at its western end. The 8th is famous for Champs Elysées and world-class hotels like the Four Seasons George V, the Plaza Athenée, and the Royal Monceau Hotel. It's a great Paris neighborhood to stay in, but it does tend to be pricier.`}
        case 'arrondissement09':
            return {title: `9th Arrondissement`, subtitle: `The Opera`, desc: `The 9th Arrondissement of Paris extends from Palais Garnier in the south to the foot of Montmartre in the north. In between are a handful of good museums and some of the most concentrated shopping in Paris. Opera, as the 9th is sometimes called, is known for the grand magasins, the 19th-century Opera Garnier, and the Grands Boulevards.`}
        case 'arrondissement10':
            return {title: `10th Arrondissement`, subtitle: `Les Gares`, desc: `While there are no Eiffel Towers or major museums here, the 10th Arrondissement is where you'll find Gare de Nord and Gare de l'Est, the two largest train stations in Paris.`}
        case 'arrondissement11':
            return {title: `11th Arrondissement`, subtitle: `Canal Saint-Martin`, desc: `This up-and-coming neighborhood straddles the canal as it winds through the 10th and 11th Arrondissements. Today it's a popular neighborhood where young Parisians live, attracted by cheaper rents and trending restaurants and cafes. You can also hop on a canal boat for a leisurely ride through the locks and on to the Seine River.`}
        case 'arrondissement12':
            return {title: `12th Arrondissement`, subtitle: `The Far East`, desc: `If you're an occasional visitor to Paris, odds are you haven't paid much attention to this big district to the east, the mighty 12th Arrondissement. But once you delve into it, you realize it's easy to spend days taking in the splendor of its attractions like Gare de Lyon, the thriving Bercy neighborhood, and the very famous market street, Rue d'Aligre.`}
        case 'arrondissement13':
            return {title: `13th Arrondissement`, subtitle: `Arts, Entertainment, and Postmodernism`, desc: `Although not as well known to visitors as some other Paris quartiers, the 13th Arrondissement nonetheless offers hidden charms, such as the thriving new arts and entertainment scene along the Seine. There's a nice contrast between tradition and modern here, from the Manufacture de Gobelins to the massive postmodern Mitterrand Library. The 13th Arrondissement is definitely worth investigation.`}
        case 'arrondissement14':
            return {title: `14th Arrondissement`, subtitle: `The South`, desc: `There's a lot for travelers to explore in the 14th Arrondissement — from the Catacombs to Boulevard Montparnasse to the Observatory of Paris. So, if you want to get away from the tourist crowds, come along on a virtual walk to a dozen highlights of the district so many Parisians call home: nearly 140,000 of them live here and make full use of the shopping streets, the markets, the schools, and the parks.`}
        case 'arrondissement15':
            return {title: `15th Arrondissement`, subtitle: `The Far Left Bank`, desc: `We love spending time in this charming southwestern arrondissement — it truly is a hidden gem of Paris. Just south of the Eiffel Tower, starting at the Champ de Mars, the 15th Arrondissement is living, breathing proof that there's a lot of Paris to see beyond the iconic monuments. There's a true neighborhood feeling; streets lined with shops, restaurants, salons, markets, and boulangeries, but there are also world-class museums and parks.`}
        case 'arrondissement16':
            return {title: `16th Arrondissement`, subtitle: `Passy and Bois de Boulogne`, desc: `The 16th Arrondissement is large and elegant, filled with streets, shops, and parks for visitors to explore. Located across the Seine from the Eiffel Tower in the southwest corner of Paris, the 16th is filled with upscale residential neighborhoods such as Passy, Auteuil and Trocadero.`}
        case 'arrondissement17':
            return {title: `17th Arrondissement`, subtitle: `Ternes`, desc: `The large 17th Arrondissement of Paris starts at the Arc de Triomphe and holds down the northwest corner of the city. It is vast — three times the size of the center, where you find the Louvre, and much else. But the advantages of the 17th are many; to begin with, there are no tourist crowds, instead you find upscale neighborhoods filled with wonderful shops, markets, hotels, museums, and parks. Here, you enjoy “la vie Parisien” — life like a local — yet you're close to the Champs-Elysées and all the other attractions and sights of the city.`}
        case 'arrondissement18':
            return {title: `18th Arrondissement`, subtitle: `Montmartre`, desc: `The quartier of Montmartre was formerly a village of the same name, high up on the hill above Paris. It encompasses the 18th Arrondissement, which runs up from the border of the 9th right up to the northernmost edge of the city. This hilltop neighborhood has been home to famous (and not-so-famous) painters and writers, most notably Picasso, Renoir, and van Gogh. From its perch on a hill, Montmartre has spectacular views, especially from the big white church of Sacre Coeur. It's also home to the Moulin Rouge.`}
        case 'arrondissement19':
            return {title: `19th Arrondissement`, subtitle: `Music, Science, and Parks`, desc: `A bustling neighborhood, with one of the largest populations in Paris, the 19th Arrondissement offers a lot to explore. Home to Parc de la Villette, which features a cluster of museums including the Cité des Sciences, Cité de la Musique, and the spectacular Philharmonie de Paris, one of the world's great concert halls. The 19th's other large park, Buttes Chaumont, sports a tall waterfall, nature walking paths, and a pedestrian bridge.`}
        case 'arrondissement20':
            return {title: `20th Arrondissement`, subtitle: `Belleville`, desc: `On the eastern edge of Paris, the 20th Arrondissement is a long, half-hour Metro ride from central Paris. It's where you find the fascinating Pere Lachaise Cemetery, final resting place of the rich and infamous. The 20th is also worth visiting for the bustling community of Belleville.`}
        case 'islands':
            return {title: `The Islands of Paris`, desc: `It's not every world capital that has two islands in the middle of the city. As you cross over the Seine towards Île de la Cité, the ancient heart of Paris, you journey back through the centuries to the very origins of the city. Along with Île Saint-Louis, the islands link the Right Bank to the Left Bank by a number of bridges — Pont Neuf is the oldest and probably the most famous. And that's where we'll start our journey into the secrets, history, and facts about the islands of Paris.`}
        case 'defense':
            return {title: `La Defense Arrondissement`, subtitle: `The Modern Business District`, desc: `La Défense is the modern business district of Paris, located six or seven kilometers west of the central city but very visible (due to its collection of soaring skyscrapers) from such vantage points as the Arc de Triomphe, the Eiffel Tower, and even Montmartre. It surprised us to learn that this modernistic collection of buildings gets eight million visitors a year.`}
        default:
            return {title: "none", desc: `Paris is divided into administrative zones called “arrondissements.” They are sometimes referred to as the "twenty small cities of Paris," each with a distinct personality and even their own town halls. Previously there were 20 arrondissements, but in 2020, the first four zones were consolidated into a new administrative district named “Paris Central,” meaning that there are now 17 neighborhoods. Here, you can explore the original 20 arrondissements — most Parisians still think of their city as being divided that way!`}
    }
}